### ISSUE TITLE
Input dispatching timed out [ANDROID]

### ISSUE THREAD

**Issue by favazHF** [amplitude/Amplitude-Flutter#212]
## Expected Behavior
It is hoped that this bug will not occur in production, as users are experiencing application crashes or long loading times.

## Current Behavior
ARN error:

```
at com.amplitude.core.platform.Mediator.applyClosure (Mediator.kt:8)
The main thread is blocked here. It is waiting, trying to acquire lock 0x0392f8ad (java.util.ArrayList), held by thread 132. [Learn more](https://developer.android.com/topic/performance/anrs/find-unresponsive-thread#lock-contention)

  at com.amplitude.core.platform.Timeline.applyClosure (Timeline.kt:34)
  at com.amplitude.core.Amplitude.flush (Amplitude.kt:5)
  at com.amplitude.amplitude_flutter.AmplitudeFlutterPlugin.onMethodCall (AmplitudeFlutterPlugin.kt:171)
  at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage (MethodChannel.java:18)
  at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler (DartMessenger.java:19)
  at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0 (DartMessenger.java:42)
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loopOnce (Looper.java:233)
  at android.os.Looper.loop (Looper.java:344)
  at android.app.ActivityThread.main (ActivityThread.java:8212)
  at java.lang.reflect.Method.invoke (Native method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:584)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1034)
```

## Steps to Reproduce
 

1. add amplitude_flutter: ^4.0.0-beta.1 in your pubspec.yaml
2. run on android device
3. It is not easy to replicate, as the console does not throw errors but internally it fails.

## Environment
[✓] Flutter (Channel stable, 3.24.5, on macOS 14.6.1 23G93 darwin-arm64 (Rosetta), locale en-CL)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)

- Device: [OnePlus Nord (OnePlus Nord)] (Multiples devices)
- Device OS and Version: [Android 12 (SDK 31)] (Multiples versions and OS)

**Comment by etozheluka** [comment]
Any updates? Have same problem on native-android build

version "1.+"

io.sentry.android.core.ApplicationNotResponding: Background ANR
    at com.amplitude.core.platform.Mediator.applyClosure(Mediator.kt:56)
    at com.amplitude.core.platform.Timeline.applyClosure(Timeline.kt:63)
    at com.amplitude.core.Amplitude.flush(Amplitude.kt:487)
    at com.space.toolkit.analytics.trackers.amplitude.SPAmplitudeTracker.flush(SPAmplitudeTracker.kt:35)
    at com.space.toolkit.analytics.core.SPAnalyticsImpl.flush(SPAnalyticsImpl.kt:22)
    at com.space.core.presentation.base.activity.SPBaseActivity.onStop(SPBaseActivity.kt:117)
    at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1644)
    at android.app.Activity.performStop(Activity.java:9312)
    at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:6352)
    at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:6332)
    at android.app.ActivityThread.handleStopActivity(ActivityThread.java:6416)
    at android.app.servertransaction.StopActivityItem.execute(StopActivityItem.java:43)
    at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:194)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:106)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:3067)
    at android.os.Handler.dispatchMessage(Handler.java:117)
    at android.os.Looper.loopOnce(Looper.java:210)
    at android.os.Looper.loop(Looper.java:302)
    at android.app.ActivityThread.main(ActivityThread.java:9652)
    at java.lang.reflect.Method.invoke
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:601)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1062)

**Comment by polbins** [comment]
Hello @favazHF, can you try a new build please? [Amplitude-Kotlin](https://github.com/amplitude/Amplitude-Kotlin) was updated with `v1.20.4` recently, so you can see if the issue still persists in that version.
