### ISSUE TITLE
app crashed in release

### ISSUE THREAD

**Issue by kalyujniy** [amplitude/Amplitude-Flutter#71]
This has been fixed in amplitude_flutter 3.4.0. Thanks.

_Originally posted by @yuhao900914 in https://github.com/amplitude/Amplitude-Flutter/issues/67#issuecomment-928162373_

After update plugin in debug mode all works fine, but when i build release app crashed with this error

Caused by: android.view.InflateException: Binary XML file line #11 in com.android.chrome:layout/0_resource_name_obfuscated: Error inflating class
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Constructor.newInstance0(Native Method)
at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
at android.view.LayoutInflater.createView(LayoutInflater.java:854)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1231)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:1119)
at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)
at android.view.LayoutInflater.inflate(LayoutInflater.java:656)
at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
at ED1.a(chromium-TrichromeChromeGoogle.aab-stable-460606133:3)
at Cl4.b(chromium-TrichromeChromeGoogle.aab-stable-460606133:7)
at jn0.run(chromium-TrichromeChromeGoogle.aab-stable-460606133:4)
at LN.run(chromium-TrichromeChromeGoogle.aab-stable-460606133:10)
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:336)
at android.os.Looper.loop(Looper.java:174)
at android.app.ActivityThread.main(ActivityThread.java:7356)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

Caused by: java.lang.IllegalArgumentException: ChromeColors requires a value for the com.android.chrome:attr/0_resource_name_obfuscated attribute to be set in your app theme. You can either set the attribute in your theme or update your theme to inherit from Theme.MaterialComponents (or a descendant).
at PQ1.c(chromium-TrichromeChromeGoogle.aab-stable-460606133:5)
at HV.b(chromium-TrichromeChromeGoogle.aab-stable-460606133:3)
at org.chromium.chrome.browser.compositor.CompositorView.g(chromium-TrichromeChromeGoogle.aab-stable-460606133:4)
at org.chromium.chrome.browser.compositor.CompositorView.(chromium-TrichromeChromeGoogle.aab-stable-460606133:5)
at org.chromium.chrome.browser.compositor.CompositorViewHolder.(chromium-TrichromeChromeGoogle.aab-stable-460606133:15)
at java.lang.reflect.Constructor.newInstance0(Native Method)
at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
at android.view.LayoutInflater.createView(LayoutInflater.java:854)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1231)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:1119)
at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)
at android.view.LayoutInflater.inflate(LayoutInflater.java:656)
at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
at ED1.a(chromium-TrichromeChromeGoogle.aab-stable-460606133:3)
at Cl4.b(chromium-TrichromeChromeGoogle.aab-stable-460606133:7)
at jn0.run(chromium-TrichromeChromeGoogle.aab-stable-460606133:4)
at LN.run(chromium-TrichromeChromeGoogle.aab-stable-460606133:10)
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:336)
at android.os.Looper.loop(Looper.java:174)
at android.app.ActivityThread.main(ActivityThread.java:7356)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
2021-10-01 09:18:47.948 13380-13380/? E/ocessService0:: Not starting debugger since process cannot load the jdwp agent.
2021-10-01 09:18:58.459 4461-12883/? E/memtrack: Couldn't load memtrack module
2021-10-01 09:19:31.825 2060-7208/? E/memtrack: Couldn't load memtrack module

when i remove amplitude plugin and build app all works fine

**Comment by yuhao900914** [comment]
I'm trying to build a release app in APK and in the App bundle, all works fine. (
https://flutter.dev/docs/deployment/android)

By looking into your app crash error, I didn't see anything related to amplitude. Those two are all caused by the com.android.chrome.
