### ISSUE TITLE
Build error on iOS during pod install

### ISSUE THREAD

**Issue by omzer** [amplitude/Amplitude-Flutter#88]
## Expected Behavior
Project build with no errors.

## Current Behavior
When building for iOS, I'm getting this error:

```
Running pod install...
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `amplitude_flutter` from `.symlinks/plugins/amplitude_flutter/ios`

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_f_4_d.txt exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/f/4/d/Amplitude/8.4.0/Amplitude.podspec.json exists! Returning local because checking is only performed in repo update
    [!] CocoaPods could not find compatible versions for pod "Amplitude":
      In Podfile:
        amplitude_flutter (from `.symlinks/plugins/amplitude_flutter/ios`) was resolved to 0.0.1, which depends on
          Amplitude (= 8.5.0)

    None of your spec sources contain a spec satisfying the dependency: `Amplitude (= 8.5.0)`.

    You have either:
     * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
     * mistyped the name or version.
     * not added the source repo that hosts the Podspec to your Podfile.

    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:317:in `raise_error_unless_state'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:299:in `block in unwind_for_conflict'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:297:in `tap'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:297:in `unwind_for_conflict'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:257:in `process_topmost_state'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:182:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/resolver.rb:94:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:1078:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:1076:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:416:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:241:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:240:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:161:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'

Error: CocoaPods's specs repository is too out-of-date to satisfy dependencies.
To update the CocoaPods specs, run:
  pod repo update

Error running pod install
Error launching application on iPhone 13.
```

## Steps to Reproduce
1. Create any fresh flutter project.
2. Add ```platform :ios, '10.0'``` to your Podfile.
3. Add ```amplitude_flutter: 3.8.0``` to pubspec.yaml file.
4. Run on iOS simulator.

Worth mentioning that it is even failing on the provided [example](https://github.com/amplitude/Amplitude-Flutter/tree/main/example) on the repo.

## Environment
- Dart SDK Version: 2.14.3
- Flutter Version: 2.5.2
- Device: iPhone 13 simulator
- Device OS and Version: iOS 15

**Comment by justin-fiedler** [comment]
Hi @omzer thanks for reaching out. We tried to reproduce the issue in a new Flutter app and in the example but have not been able to recreate it so far.

I noticed the mention of `pod repo update` in the error output. Could you please try this and then try again?

If that doesn't fix the issue could you please run ` flutter doctor` and share the output.

Thank you!

**Comment by omzer** [comment]
@justin-fiedler Tried ```pod repo update``` and made no difference.
This is the result of the flutter doctor:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.2, on macOS 12.0.1 21A559 darwin-arm, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Community Edition (version 2021.1.3)
[✓] VS Code (version 1.62.3)
[✓] Connected device (1 available)
```

I also tried to update to the latest flutter version (2.5.3) and the issue still reproducing.

**Comment by omzer** [comment]
@justin-fiedler I did the following:
- Re-installed xcode.
- Removed Podfile/Podfile.lock.
- flutter clean.
- flutter pub get.
- New run.
- Added ```platform :ios, '10.0'``` to the Podfile.

And now, the previous error is gone, however I'm getting a new one:

```
Running pod install...
Running Xcode build...
Xcode build done.                                            2.4s
Failed to build iOS app
Error output from Xcode build:
↳
    --- xcodebuild: WARNING: Using the first of multiple matching destinations:
    { platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
    { platform:iOS Simulator, id:XXXXX3, OS:15.0, name:iPhone 13 }
    { platform:macOS, arch:arm64, variant:Designed for [iPad,iPhone], id:XXXXE }
    { platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
    { platform:iOS, id:XXXXA, name:Omar’s iPhone }
    ** BUILD FAILED **


Xcode's output:
↳
    /Users/omar/Desktop/3mr/programs/flutter/.pub-cache/hosted/pub.dartlang.org/amplitude_flutter-3.8.0/ios/Classes/SwiftAmplitudeFlutterPlugin.swift:127:64: warning: 'logRevenue(_:quantity:price:)' is deprecated: Use `logRevenueV2` and `AMPRevenue` instead
                        Amplitude.instance(withName: instanceName).logRevenue(productIdentifier,
                                                                   ^
    /Users/omar/Desktop/3mr/programs/flutter/.pub-cache/hosted/pub.dartlang.org/amplitude_flutter-3.8.0/ios/Classes/SwiftAmplitudeFlutterPlugin.swift:134:64: warning: 'logRevenue' is deprecated: Use `logRevenueV2` and `AMPRevenue` instead
                        Amplitude.instance(withName: instanceName).logRevenue(NSNumber(value: amount))
                                                                   ^
    /Users/omar/Desktop/3mr/programs/flutter/.pub-cache/hosted/pub.dartlang.org/amplitude_flutter-3.8.0/ios/Classes/SwiftAmplitudeFlutterPlugin.swift:187:62: error: cannot find 'AMPServerZone' in scope
                        let ampServerZone = serverZone == "EU" ? AMPServerZone.EU : AMPServerZone.US
                                                                 ^~~~~~~~~~~~~
    /Users/omar/Desktop/3mr/programs/flutter/.pub-cache/hosted/pub.dartlang.org/amplitude_flutter-3.8.0/ios/Classes/SwiftAmplitudeFlutterPlugin.swift:187:81: error: cannot find 'AMPServerZone' in scope
                        let ampServerZone = serverZone == "EU" ? AMPServerZone.EU : AMPServerZone.US
                                                                                    ^~~~~~~~~~~~~
    /Users/omar/Desktop/3mr/programs/flutter/.pub-cache/hosted/pub.dartlang.org/amplitude_flutter-3.8.0/ios/Classes/SwiftAmplitudeFlutterPlugin.swift:188:64: error: value of type 'Amplitude' has no member 'setServerZone'
                        Amplitude.instance(withName: instanceName).setServerZone(ampServerZone, updateServerUrl: updateServerUrl)
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~
    /Users/omar/Desktop/3mr/programs/flutter/.pub-cache/hosted/pub.dartlang.org/amplitude_flutter-3.8.0/ios/Classes/SwiftAmplitudeFlutterPlugin.swift:127:64: warning: 'logRevenue(_:quantity:price:)' is deprecated: Use `logRevenueV2` and `AMPRevenue` instead
                        Amplitude.instance(withName: instanceName).logRevenue(productIdentifier,
                                                                   ^
    /Users/omar/Desktop/3mr/programs/flutter/.pub-cache/hosted/pub.dartlang.org/amplitude_flutter-3.8.0/ios/Classes/SwiftAmplitudeFlutterPlugin.swift:134:64: warning: 'logRevenue' is deprecated: Use `logRevenueV2` and `AMPRevenue` instead
                        Amplitude.instance(withName: instanceName).logRevenue(NSNumber(value: amount))
                                                                   ^
    /Users/omar/Desktop/3mr/programs/flutter/.pub-cache/hosted/pub.dartlang.org/amplitude_flutter-3.8.0/ios/Classes/SwiftAmplitudeFlutterPlugin.swift:187:62: error: cannot find 'AMPServerZone' in scope
                        let ampServerZone = serverZone == "EU" ? AMPServerZone.EU : AMPServerZone.US
                                                                 ^~~~~~~~~~~~~
    /Users/omar/Desktop/3mr/programs/flutter/.pub-cache/hosted/pub.dartlang.org/amplitude_flutter-3.8.0/ios/Classes/SwiftAmplitudeFlutterPlugin.swift:187:81: error: cannot find 'AMPServerZone' in scope
                        let ampServerZone = serverZone == "EU" ? AMPServerZone.EU : AMPServerZone.US
                                                                                    ^~~~~~~~~~~~~
    /Users/omar/Desktop/3mr/programs/flutter/.pub-cache/hosted/pub.dartlang.org/amplitude_flutter-3.8.0/ios/Classes/SwiftAmplitudeFlutterPlugin.swift:188:64: error: value of type 'Amplitude' has no member 'setServerZone'
                        Amplitude.instance(withName: instanceName).setServerZone(ampServerZone, updateServerUrl: updateServerUrl)
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in parallel

Could not build the application for the simulator.
Error launching application on iPhone 13.
```

I'm using the version 3.8 for amplitude.

**Comment by yuhao900914** [comment]
@omzer  Since you re-installed the Xcode, did you login into Xcode?  
If not, please open the project's Runner.xcworkspace file and log into Xcode at: "Signing & Capabilities" -> "All" -> "Signing".

**Comment by omzer** [comment]
@yuhao900914 Did that, unfortunately changed nothing.
If the issue is not reproducing in your end, then mostly it is something releated to my setup, I'll close this issue for now.
